// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/discover/v1/discover_api.proto

package discoverv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DiscoverRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiscoverRequest) Reset()         { *m = DiscoverRequest{} }
func (m *DiscoverRequest) String() string { return proto.CompactTextString(m) }
func (*DiscoverRequest) ProtoMessage()    {}
func (*DiscoverRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{0}
}

func (m *DiscoverRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverRequest.Unmarshal(m, b)
}
func (m *DiscoverRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverRequest.Marshal(b, m, deterministic)
}
func (m *DiscoverRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverRequest.Merge(m, src)
}
func (m *DiscoverRequest) XXX_Size() int {
	return xxx_messageInfo_DiscoverRequest.Size(m)
}
func (m *DiscoverRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverRequest proto.InternalMessageInfo

type DiscoverResponse struct {
	GoStruct             string     `protobuf:"bytes,1,opt,name=goStruct,proto3" json:"goStruct,omitempty"`
	ServiceName          string     `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceDescription   string     `protobuf:"bytes,3,opt,name=serviceDescription,proto3" json:"serviceDescription,omitempty"`
	Component            *Component `protobuf:"bytes,4,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DiscoverResponse) Reset()         { *m = DiscoverResponse{} }
func (m *DiscoverResponse) String() string { return proto.CompactTextString(m) }
func (*DiscoverResponse) ProtoMessage()    {}
func (*DiscoverResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{1}
}

func (m *DiscoverResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverResponse.Unmarshal(m, b)
}
func (m *DiscoverResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverResponse.Marshal(b, m, deterministic)
}
func (m *DiscoverResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverResponse.Merge(m, src)
}
func (m *DiscoverResponse) XXX_Size() int {
	return xxx_messageInfo_DiscoverResponse.Size(m)
}
func (m *DiscoverResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverResponse proto.InternalMessageInfo

func (m *DiscoverResponse) GetGoStruct() string {
	if m != nil {
		return m.GoStruct
	}
	return ""
}

func (m *DiscoverResponse) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *DiscoverResponse) GetServiceDescription() string {
	if m != nil {
		return m.ServiceDescription
	}
	return ""
}

func (m *DiscoverResponse) GetComponent() *Component {
	if m != nil {
		return m.Component
	}
	return nil
}

type Component struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Sources              []*Source     `protobuf:"bytes,3,rep,name=sources,proto3" json:"sources,omitempty"`
	Processors           []*Processor  `protobuf:"bytes,4,rep,name=processors,proto3" json:"processors,omitempty"`
	Sinks                []*Sink       `protobuf:"bytes,5,rep,name=sinks,proto3" json:"sinks,omitempty"`
	Views                []*View       `protobuf:"bytes,6,rep,name=views,proto3" json:"views,omitempty"`
	ViewSources          []*ViewSource `protobuf:"bytes,7,rep,name=viewSources,proto3" json:"viewSources,omitempty"`
	ViewSinks            []*ViewSink   `protobuf:"bytes,8,rep,name=viewSinks,proto3" json:"viewSinks,omitempty"`
	Persistence          *Persistence  `protobuf:"bytes,9,opt,name=persistence,proto3" json:"persistence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{2}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Component) GetSources() []*Source {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Component) GetProcessors() []*Processor {
	if m != nil {
		return m.Processors
	}
	return nil
}

func (m *Component) GetSinks() []*Sink {
	if m != nil {
		return m.Sinks
	}
	return nil
}

func (m *Component) GetViews() []*View {
	if m != nil {
		return m.Views
	}
	return nil
}

func (m *Component) GetViewSources() []*ViewSource {
	if m != nil {
		return m.ViewSources
	}
	return nil
}

func (m *Component) GetViewSinks() []*ViewSink {
	if m != nil {
		return m.ViewSinks
	}
	return nil
}

func (m *Component) GetPersistence() *Persistence {
	if m != nil {
		return m.Persistence
	}
	return nil
}

type Defaults struct {
	Partition            int64              `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Replication          int64              `protobuf:"varint,2,opt,name=replication,proto3" json:"replication,omitempty"`
	Type                 string             `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Retention            *duration.Duration `protobuf:"bytes,4,opt,name=retention,proto3" json:"retention,omitempty"`
	Segment              *duration.Duration `protobuf:"bytes,5,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Defaults) Reset()         { *m = Defaults{} }
func (m *Defaults) String() string { return proto.CompactTextString(m) }
func (*Defaults) ProtoMessage()    {}
func (*Defaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{3}
}

func (m *Defaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Defaults.Unmarshal(m, b)
}
func (m *Defaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Defaults.Marshal(b, m, deterministic)
}
func (m *Defaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Defaults.Merge(m, src)
}
func (m *Defaults) XXX_Size() int {
	return xxx_messageInfo_Defaults.Size(m)
}
func (m *Defaults) XXX_DiscardUnknown() {
	xxx_messageInfo_Defaults.DiscardUnknown(m)
}

var xxx_messageInfo_Defaults proto.InternalMessageInfo

func (m *Defaults) GetPartition() int64 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *Defaults) GetReplication() int64 {
	if m != nil {
		return m.Replication
	}
	return 0
}

func (m *Defaults) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Defaults) GetRetention() *duration.Duration {
	if m != nil {
		return m.Retention
	}
	return nil
}

func (m *Defaults) GetSegment() *duration.Duration {
	if m != nil {
		return m.Segment
	}
	return nil
}

type DiscoverInfo struct {
	ServiceName          string     `protobuf:"bytes,1,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	ServiceDescription   string     `protobuf:"bytes,2,opt,name=serviceDescription,proto3" json:"serviceDescription,omitempty"`
	Component            *Component `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DiscoverInfo) Reset()         { *m = DiscoverInfo{} }
func (m *DiscoverInfo) String() string { return proto.CompactTextString(m) }
func (*DiscoverInfo) ProtoMessage()    {}
func (*DiscoverInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{4}
}

func (m *DiscoverInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscoverInfo.Unmarshal(m, b)
}
func (m *DiscoverInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscoverInfo.Marshal(b, m, deterministic)
}
func (m *DiscoverInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscoverInfo.Merge(m, src)
}
func (m *DiscoverInfo) XXX_Size() int {
	return xxx_messageInfo_DiscoverInfo.Size(m)
}
func (m *DiscoverInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscoverInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DiscoverInfo proto.InternalMessageInfo

func (m *DiscoverInfo) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *DiscoverInfo) GetServiceDescription() string {
	if m != nil {
		return m.ServiceDescription
	}
	return ""
}

func (m *DiscoverInfo) GetComponent() *Component {
	if m != nil {
		return m.Component
	}
	return nil
}

type Input struct {
	TopicDefinition      *TopicDefinition `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{5}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

type Join struct {
	TopicDefinition      *TopicDefinition `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{6}
}

func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

type Lookup struct {
	TopicDefinition      *TopicDefinition `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Lookup) Reset()         { *m = Lookup{} }
func (m *Lookup) String() string { return proto.CompactTextString(m) }
func (*Lookup) ProtoMessage()    {}
func (*Lookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{7}
}

func (m *Lookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lookup.Unmarshal(m, b)
}
func (m *Lookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lookup.Marshal(b, m, deterministic)
}
func (m *Lookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lookup.Merge(m, src)
}
func (m *Lookup) XXX_Size() int {
	return xxx_messageInfo_Lookup.Size(m)
}
func (m *Lookup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lookup.DiscardUnknown(m)
}

var xxx_messageInfo_Lookup proto.InternalMessageInfo

func (m *Lookup) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

type MessageDefinitions struct {
	Protobuf             []string `protobuf:"bytes,1,rep,name=protobuf,proto3" json:"protobuf,omitempty"`
	Avro                 []string `protobuf:"bytes,2,rep,name=avro,proto3" json:"avro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageDefinitions) Reset()         { *m = MessageDefinitions{} }
func (m *MessageDefinitions) String() string { return proto.CompactTextString(m) }
func (*MessageDefinitions) ProtoMessage()    {}
func (*MessageDefinitions) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{8}
}

func (m *MessageDefinitions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageDefinitions.Unmarshal(m, b)
}
func (m *MessageDefinitions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageDefinitions.Marshal(b, m, deterministic)
}
func (m *MessageDefinitions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageDefinitions.Merge(m, src)
}
func (m *MessageDefinitions) XXX_Size() int {
	return xxx_messageInfo_MessageDefinitions.Size(m)
}
func (m *MessageDefinitions) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageDefinitions.DiscardUnknown(m)
}

var xxx_messageInfo_MessageDefinitions proto.InternalMessageInfo

func (m *MessageDefinitions) GetProtobuf() []string {
	if m != nil {
		return m.Protobuf
	}
	return nil
}

func (m *MessageDefinitions) GetAvro() []string {
	if m != nil {
		return m.Avro
	}
	return nil
}

type Messages struct {
	Protobuf             []string `protobuf:"bytes,1,rep,name=protobuf,proto3" json:"protobuf,omitempty"`
	Avro                 []string `protobuf:"bytes,2,rep,name=avro,proto3" json:"avro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Messages) Reset()         { *m = Messages{} }
func (m *Messages) String() string { return proto.CompactTextString(m) }
func (*Messages) ProtoMessage()    {}
func (*Messages) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{9}
}

func (m *Messages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Messages.Unmarshal(m, b)
}
func (m *Messages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Messages.Marshal(b, m, deterministic)
}
func (m *Messages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Messages.Merge(m, src)
}
func (m *Messages) XXX_Size() int {
	return xxx_messageInfo_Messages.Size(m)
}
func (m *Messages) XXX_DiscardUnknown() {
	xxx_messageInfo_Messages.DiscardUnknown(m)
}

var xxx_messageInfo_Messages proto.InternalMessageInfo

func (m *Messages) GetProtobuf() []string {
	if m != nil {
		return m.Protobuf
	}
	return nil
}

func (m *Messages) GetAvro() []string {
	if m != nil {
		return m.Avro
	}
	return nil
}

type Output struct {
	TopicDefinition      *TopicDefinition `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{10}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *Output) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type OutputSettings struct {
	Package              string   `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Module               string   `protobuf:"bytes,3,opt,name=module,proto3" json:"module,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputSettings) Reset()         { *m = OutputSettings{} }
func (m *OutputSettings) String() string { return proto.CompactTextString(m) }
func (*OutputSettings) ProtoMessage()    {}
func (*OutputSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{11}
}

func (m *OutputSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputSettings.Unmarshal(m, b)
}
func (m *OutputSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputSettings.Marshal(b, m, deterministic)
}
func (m *OutputSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputSettings.Merge(m, src)
}
func (m *OutputSettings) XXX_Size() int {
	return xxx_messageInfo_OutputSettings.Size(m)
}
func (m *OutputSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputSettings.DiscardUnknown(m)
}

var xxx_messageInfo_OutputSettings proto.InternalMessageInfo

func (m *OutputSettings) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *OutputSettings) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *OutputSettings) GetModule() string {
	if m != nil {
		return m.Module
	}
	return ""
}

type Persistence struct {
	TopicDefinition         *TopicDefinition         `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	TopicCreationDefinition *TopicCreationDefinition `protobuf:"bytes,2,opt,name=topicCreationDefinition,proto3" json:"topicCreationDefinition,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *Persistence) Reset()         { *m = Persistence{} }
func (m *Persistence) String() string { return proto.CompactTextString(m) }
func (*Persistence) ProtoMessage()    {}
func (*Persistence) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{12}
}

func (m *Persistence) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Persistence.Unmarshal(m, b)
}
func (m *Persistence) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Persistence.Marshal(b, m, deterministic)
}
func (m *Persistence) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Persistence.Merge(m, src)
}
func (m *Persistence) XXX_Size() int {
	return xxx_messageInfo_Persistence.Size(m)
}
func (m *Persistence) XXX_DiscardUnknown() {
	xxx_messageInfo_Persistence.DiscardUnknown(m)
}

var xxx_messageInfo_Persistence proto.InternalMessageInfo

func (m *Persistence) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *Persistence) GetTopicCreationDefinition() *TopicCreationDefinition {
	if m != nil {
		return m.TopicCreationDefinition
	}
	return nil
}

type Processor struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	GroupNameOverride    string       `protobuf:"bytes,2,opt,name=groupNameOverride,proto3" json:"groupNameOverride,omitempty"`
	Description          string       `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Inputs               []*Input     `protobuf:"bytes,4,rep,name=inputs,proto3" json:"inputs,omitempty"`
	Lookups              []*Lookup    `protobuf:"bytes,5,rep,name=lookups,proto3" json:"lookups,omitempty"`
	Joins                []*Join      `protobuf:"bytes,6,rep,name=joins,proto3" json:"joins,omitempty"`
	Outputs              []*Output    `protobuf:"bytes,7,rep,name=outputs,proto3" json:"outputs,omitempty"`
	Persistence          *Persistence `protobuf:"bytes,8,opt,name=persistence,proto3" json:"persistence,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Processor) Reset()         { *m = Processor{} }
func (m *Processor) String() string { return proto.CompactTextString(m) }
func (*Processor) ProtoMessage()    {}
func (*Processor) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{13}
}

func (m *Processor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Processor.Unmarshal(m, b)
}
func (m *Processor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Processor.Marshal(b, m, deterministic)
}
func (m *Processor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Processor.Merge(m, src)
}
func (m *Processor) XXX_Size() int {
	return xxx_messageInfo_Processor.Size(m)
}
func (m *Processor) XXX_DiscardUnknown() {
	xxx_messageInfo_Processor.DiscardUnknown(m)
}

var xxx_messageInfo_Processor proto.InternalMessageInfo

func (m *Processor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Processor) GetGroupNameOverride() string {
	if m != nil {
		return m.GroupNameOverride
	}
	return ""
}

func (m *Processor) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Processor) GetInputs() []*Input {
	if m != nil {
		return m.Inputs
	}
	return nil
}

func (m *Processor) GetLookups() []*Lookup {
	if m != nil {
		return m.Lookups
	}
	return nil
}

func (m *Processor) GetJoins() []*Join {
	if m != nil {
		return m.Joins
	}
	return nil
}

func (m *Processor) GetOutputs() []*Output {
	if m != nil {
		return m.Outputs
	}
	return nil
}

func (m *Processor) GetPersistence() *Persistence {
	if m != nil {
		return m.Persistence
	}
	return nil
}

type Service struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string              `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Components           []string            `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty"`
	Output               *OutputSettings     `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Defaults             *TopicDefaults      `protobuf:"bytes,5,opt,name=defaults,proto3" json:"defaults,omitempty"`
	Messages             *MessageDefinitions `protobuf:"bytes,6,opt,name=messages,proto3" json:"messages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Service) Reset()         { *m = Service{} }
func (m *Service) String() string { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()    {}
func (*Service) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{14}
}

func (m *Service) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Service.Unmarshal(m, b)
}
func (m *Service) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Service.Marshal(b, m, deterministic)
}
func (m *Service) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Service.Merge(m, src)
}
func (m *Service) XXX_Size() int {
	return xxx_messageInfo_Service.Size(m)
}
func (m *Service) XXX_DiscardUnknown() {
	xxx_messageInfo_Service.DiscardUnknown(m)
}

var xxx_messageInfo_Service proto.InternalMessageInfo

func (m *Service) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Service) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Service) GetComponents() []string {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *Service) GetOutput() *OutputSettings {
	if m != nil {
		return m.Output
	}
	return nil
}

func (m *Service) GetDefaults() *TopicDefaults {
	if m != nil {
		return m.Defaults
	}
	return nil
}

func (m *Service) GetMessages() *MessageDefinitions {
	if m != nil {
		return m.Messages
	}
	return nil
}

type Sink struct {
	Name                 string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string           `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	TopicDefinition      *TopicDefinition `protobuf:"bytes,3,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Sink) Reset()         { *m = Sink{} }
func (m *Sink) String() string { return proto.CompactTextString(m) }
func (*Sink) ProtoMessage()    {}
func (*Sink) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{15}
}

func (m *Sink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sink.Unmarshal(m, b)
}
func (m *Sink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sink.Marshal(b, m, deterministic)
}
func (m *Sink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sink.Merge(m, src)
}
func (m *Sink) XXX_Size() int {
	return xxx_messageInfo_Sink.Size(m)
}
func (m *Sink) XXX_DiscardUnknown() {
	xxx_messageInfo_Sink.DiscardUnknown(m)
}

var xxx_messageInfo_Sink proto.InternalMessageInfo

func (m *Sink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Sink) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Sink) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

type Source struct {
	TopicDefinition         *TopicDefinition         `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	TopicCreationDefinition *TopicCreationDefinition `protobuf:"bytes,2,opt,name=topicCreationDefinition,proto3" json:"topicCreationDefinition,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *Source) Reset()         { *m = Source{} }
func (m *Source) String() string { return proto.CompactTextString(m) }
func (*Source) ProtoMessage()    {}
func (*Source) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{16}
}

func (m *Source) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Source.Unmarshal(m, b)
}
func (m *Source) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Source.Marshal(b, m, deterministic)
}
func (m *Source) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Source.Merge(m, src)
}
func (m *Source) XXX_Size() int {
	return xxx_messageInfo_Source.Size(m)
}
func (m *Source) XXX_DiscardUnknown() {
	xxx_messageInfo_Source.DiscardUnknown(m)
}

var xxx_messageInfo_Source proto.InternalMessageInfo

func (m *Source) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *Source) GetTopicCreationDefinition() *TopicCreationDefinition {
	if m != nil {
		return m.TopicCreationDefinition
	}
	return nil
}

type TopicCreationDefinition struct {
	Partitions           int64              `protobuf:"varint,1,opt,name=partitions,proto3" json:"partitions,omitempty"`
	Replicas             int64              `protobuf:"varint,2,opt,name=replicas,proto3" json:"replicas,omitempty"`
	Compact              bool               `protobuf:"varint,3,opt,name=compact,proto3" json:"compact,omitempty"`
	Retention            *duration.Duration `protobuf:"bytes,4,opt,name=retention,proto3" json:"retention,omitempty"`
	Segment              *duration.Duration `protobuf:"bytes,5,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TopicCreationDefinition) Reset()         { *m = TopicCreationDefinition{} }
func (m *TopicCreationDefinition) String() string { return proto.CompactTextString(m) }
func (*TopicCreationDefinition) ProtoMessage()    {}
func (*TopicCreationDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{17}
}

func (m *TopicCreationDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicCreationDefinition.Unmarshal(m, b)
}
func (m *TopicCreationDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicCreationDefinition.Marshal(b, m, deterministic)
}
func (m *TopicCreationDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicCreationDefinition.Merge(m, src)
}
func (m *TopicCreationDefinition) XXX_Size() int {
	return xxx_messageInfo_TopicCreationDefinition.Size(m)
}
func (m *TopicCreationDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicCreationDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_TopicCreationDefinition proto.InternalMessageInfo

func (m *TopicCreationDefinition) GetPartitions() int64 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

func (m *TopicCreationDefinition) GetReplicas() int64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *TopicCreationDefinition) GetCompact() bool {
	if m != nil {
		return m.Compact
	}
	return false
}

func (m *TopicCreationDefinition) GetRetention() *duration.Duration {
	if m != nil {
		return m.Retention
	}
	return nil
}

func (m *TopicCreationDefinition) GetSegment() *duration.Duration {
	if m != nil {
		return m.Segment
	}
	return nil
}

type TopicDefaults struct {
	Partition            int64              `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	Replication          int64              `protobuf:"varint,2,opt,name=replication,proto3" json:"replication,omitempty"`
	Type                 string             `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Retention            *duration.Duration `protobuf:"bytes,4,opt,name=retention,proto3" json:"retention,omitempty"`
	Segment              *duration.Duration `protobuf:"bytes,5,opt,name=segment,proto3" json:"segment,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TopicDefaults) Reset()         { *m = TopicDefaults{} }
func (m *TopicDefaults) String() string { return proto.CompactTextString(m) }
func (*TopicDefaults) ProtoMessage()    {}
func (*TopicDefaults) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{18}
}

func (m *TopicDefaults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicDefaults.Unmarshal(m, b)
}
func (m *TopicDefaults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicDefaults.Marshal(b, m, deterministic)
}
func (m *TopicDefaults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicDefaults.Merge(m, src)
}
func (m *TopicDefaults) XXX_Size() int {
	return xxx_messageInfo_TopicDefaults.Size(m)
}
func (m *TopicDefaults) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicDefaults.DiscardUnknown(m)
}

var xxx_messageInfo_TopicDefaults proto.InternalMessageInfo

func (m *TopicDefaults) GetPartition() int64 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *TopicDefaults) GetReplication() int64 {
	if m != nil {
		return m.Replication
	}
	return 0
}

func (m *TopicDefaults) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TopicDefaults) GetRetention() *duration.Duration {
	if m != nil {
		return m.Retention
	}
	return nil
}

func (m *TopicDefaults) GetSegment() *duration.Duration {
	if m != nil {
		return m.Segment
	}
	return nil
}

type TopicDefinition struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TopicDefinition) Reset()         { *m = TopicDefinition{} }
func (m *TopicDefinition) String() string { return proto.CompactTextString(m) }
func (*TopicDefinition) ProtoMessage()    {}
func (*TopicDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{19}
}

func (m *TopicDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicDefinition.Unmarshal(m, b)
}
func (m *TopicDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicDefinition.Marshal(b, m, deterministic)
}
func (m *TopicDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicDefinition.Merge(m, src)
}
func (m *TopicDefinition) XXX_Size() int {
	return xxx_messageInfo_TopicDefinition.Size(m)
}
func (m *TopicDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_TopicDefinition proto.InternalMessageInfo

func (m *TopicDefinition) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TopicDefinition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TopicDefinition) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type View struct {
	TopicDefinition         *TopicDefinition         `protobuf:"bytes,1,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	TopicCreationDefinition *TopicCreationDefinition `protobuf:"bytes,2,opt,name=topicCreationDefinition,proto3" json:"topicCreationDefinition,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *View) Reset()         { *m = View{} }
func (m *View) String() string { return proto.CompactTextString(m) }
func (*View) ProtoMessage()    {}
func (*View) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{20}
}

func (m *View) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_View.Unmarshal(m, b)
}
func (m *View) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_View.Marshal(b, m, deterministic)
}
func (m *View) XXX_Merge(src proto.Message) {
	xxx_messageInfo_View.Merge(m, src)
}
func (m *View) XXX_Size() int {
	return xxx_messageInfo_View.Size(m)
}
func (m *View) XXX_DiscardUnknown() {
	xxx_messageInfo_View.DiscardUnknown(m)
}

var xxx_messageInfo_View proto.InternalMessageInfo

func (m *View) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *View) GetTopicCreationDefinition() *TopicCreationDefinition {
	if m != nil {
		return m.TopicCreationDefinition
	}
	return nil
}

type ViewSink struct {
	Name                    string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TopicDefinition         *TopicDefinition         `protobuf:"bytes,2,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	TopicCreationDefinition *TopicCreationDefinition `protobuf:"bytes,3,opt,name=topicCreationDefinition,proto3" json:"topicCreationDefinition,omitempty"`
	Description             string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *ViewSink) Reset()         { *m = ViewSink{} }
func (m *ViewSink) String() string { return proto.CompactTextString(m) }
func (*ViewSink) ProtoMessage()    {}
func (*ViewSink) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{21}
}

func (m *ViewSink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSink.Unmarshal(m, b)
}
func (m *ViewSink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSink.Marshal(b, m, deterministic)
}
func (m *ViewSink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSink.Merge(m, src)
}
func (m *ViewSink) XXX_Size() int {
	return xxx_messageInfo_ViewSink.Size(m)
}
func (m *ViewSink) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSink.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSink proto.InternalMessageInfo

func (m *ViewSink) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewSink) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *ViewSink) GetTopicCreationDefinition() *TopicCreationDefinition {
	if m != nil {
		return m.TopicCreationDefinition
	}
	return nil
}

func (m *ViewSink) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ViewSource struct {
	Name                    string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	TopicDefinition         *TopicDefinition         `protobuf:"bytes,2,opt,name=topicDefinition,proto3" json:"topicDefinition,omitempty"`
	TopicCreationDefinition *TopicCreationDefinition `protobuf:"bytes,3,opt,name=topicCreationDefinition,proto3" json:"topicCreationDefinition,omitempty"`
	Description             string                   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                 `json:"-"`
	XXX_unrecognized        []byte                   `json:"-"`
	XXX_sizecache           int32                    `json:"-"`
}

func (m *ViewSource) Reset()         { *m = ViewSource{} }
func (m *ViewSource) String() string { return proto.CompactTextString(m) }
func (*ViewSource) ProtoMessage()    {}
func (*ViewSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ea9856dc561108c, []int{22}
}

func (m *ViewSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ViewSource.Unmarshal(m, b)
}
func (m *ViewSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ViewSource.Marshal(b, m, deterministic)
}
func (m *ViewSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ViewSource.Merge(m, src)
}
func (m *ViewSource) XXX_Size() int {
	return xxx_messageInfo_ViewSource.Size(m)
}
func (m *ViewSource) XXX_DiscardUnknown() {
	xxx_messageInfo_ViewSource.DiscardUnknown(m)
}

var xxx_messageInfo_ViewSource proto.InternalMessageInfo

func (m *ViewSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ViewSource) GetTopicDefinition() *TopicDefinition {
	if m != nil {
		return m.TopicDefinition
	}
	return nil
}

func (m *ViewSource) GetTopicCreationDefinition() *TopicCreationDefinition {
	if m != nil {
		return m.TopicCreationDefinition
	}
	return nil
}

func (m *ViewSource) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*DiscoverRequest)(nil), "kafmesh.discover.v1.DiscoverRequest")
	proto.RegisterType((*DiscoverResponse)(nil), "kafmesh.discover.v1.DiscoverResponse")
	proto.RegisterType((*Component)(nil), "kafmesh.discover.v1.Component")
	proto.RegisterType((*Defaults)(nil), "kafmesh.discover.v1.Defaults")
	proto.RegisterType((*DiscoverInfo)(nil), "kafmesh.discover.v1.DiscoverInfo")
	proto.RegisterType((*Input)(nil), "kafmesh.discover.v1.Input")
	proto.RegisterType((*Join)(nil), "kafmesh.discover.v1.Join")
	proto.RegisterType((*Lookup)(nil), "kafmesh.discover.v1.Lookup")
	proto.RegisterType((*MessageDefinitions)(nil), "kafmesh.discover.v1.MessageDefinitions")
	proto.RegisterType((*Messages)(nil), "kafmesh.discover.v1.Messages")
	proto.RegisterType((*Output)(nil), "kafmesh.discover.v1.Output")
	proto.RegisterType((*OutputSettings)(nil), "kafmesh.discover.v1.OutputSettings")
	proto.RegisterType((*Persistence)(nil), "kafmesh.discover.v1.Persistence")
	proto.RegisterType((*Processor)(nil), "kafmesh.discover.v1.Processor")
	proto.RegisterType((*Service)(nil), "kafmesh.discover.v1.Service")
	proto.RegisterType((*Sink)(nil), "kafmesh.discover.v1.Sink")
	proto.RegisterType((*Source)(nil), "kafmesh.discover.v1.Source")
	proto.RegisterType((*TopicCreationDefinition)(nil), "kafmesh.discover.v1.TopicCreationDefinition")
	proto.RegisterType((*TopicDefaults)(nil), "kafmesh.discover.v1.TopicDefaults")
	proto.RegisterType((*TopicDefinition)(nil), "kafmesh.discover.v1.TopicDefinition")
	proto.RegisterType((*View)(nil), "kafmesh.discover.v1.View")
	proto.RegisterType((*ViewSink)(nil), "kafmesh.discover.v1.ViewSink")
	proto.RegisterType((*ViewSource)(nil), "kafmesh.discover.v1.ViewSource")
}

func init() {
	proto.RegisterFile("kafmesh/discover/v1/discover_api.proto", fileDescriptor_5ea9856dc561108c)
}

var fileDescriptor_5ea9856dc561108c = []byte{
	// 1048 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0xdd, 0x8e, 0xdb, 0x44,
	0x14, 0x96, 0xe3, 0xfc, 0x38, 0x27, 0xd0, 0xa5, 0x53, 0x44, 0xdd, 0x05, 0x96, 0xc8, 0xfc, 0xed,
	0x45, 0xe5, 0x68, 0x53, 0x21, 0x24, 0x8a, 0x2a, 0xd1, 0x8d, 0x84, 0xca, 0x4f, 0x8b, 0x26, 0xb0,
	0x20, 0x24, 0x84, 0x5c, 0x67, 0x92, 0x0e, 0x49, 0x3c, 0x66, 0x66, 0x9c, 0x0a, 0x1e, 0x80, 0x2b,
	0x9e, 0x01, 0x89, 0x5b, 0x1e, 0x02, 0x71, 0xc3, 0x1d, 0x37, 0x3c, 0x00, 0x3c, 0x07, 0xe2, 0x0a,
	0xcd, 0x78, 0xc6, 0x76, 0x13, 0x67, 0xb7, 0x5d, 0xb6, 0x48, 0x4b, 0xef, 0xe6, 0xe7, 0xfb, 0xc6,
	0xe7, 0x78, 0xce, 0x77, 0xce, 0xb1, 0xe1, 0xb5, 0x79, 0x34, 0x5d, 0x12, 0x71, 0x6f, 0x30, 0xa1,
	0x22, 0x66, 0x2b, 0xc2, 0x07, 0xab, 0x83, 0x62, 0xfc, 0x65, 0x94, 0xd2, 0x30, 0xe5, 0x4c, 0x32,
	0x74, 0xc9, 0xe0, 0x42, 0xbb, 0x17, 0xae, 0x0e, 0x76, 0xf7, 0x66, 0x8c, 0xcd, 0x16, 0x64, 0xa0,
	0x21, 0x77, 0xb3, 0xe9, 0x60, 0x92, 0xf1, 0x48, 0x52, 0x96, 0xe4, 0xa4, 0xe0, 0x22, 0xec, 0x8c,
	0x0c, 0x1c, 0x93, 0xaf, 0x33, 0x22, 0x64, 0xf0, 0xb3, 0x03, 0xcf, 0x94, 0x6b, 0x22, 0x65, 0x89,
	0x20, 0x68, 0x17, 0xbc, 0x19, 0x1b, 0x4b, 0x9e, 0xc5, 0xd2, 0x77, 0xfa, 0xce, 0x7e, 0x17, 0x17,
	0x73, 0xd4, 0x87, 0x9e, 0x20, 0x7c, 0x45, 0x63, 0x72, 0x3b, 0x5a, 0x12, 0xbf, 0xa1, 0xb7, 0xab,
	0x4b, 0x28, 0x04, 0x64, 0xa6, 0x23, 0x22, 0x62, 0x4e, 0x53, 0x65, 0x81, 0xef, 0x6a, 0x60, 0xcd,
	0x0e, 0x7a, 0x1b, 0xba, 0x31, 0x5b, 0xa6, 0x2c, 0x21, 0x89, 0xf4, 0x9b, 0x7d, 0x67, 0xbf, 0x37,
	0xdc, 0x0b, 0x6b, 0xdc, 0x0b, 0x0f, 0x2d, 0x0a, 0x97, 0x84, 0xe0, 0x4f, 0x17, 0xba, 0xc5, 0x06,
	0x42, 0xd0, 0x4c, 0x94, 0x59, 0xb9, 0xd5, 0x7a, 0xac, 0x2c, 0x9e, 0x54, 0x0c, 0x31, 0x16, 0x57,
	0x96, 0xd0, 0x1b, 0xd0, 0x11, 0x2c, 0xe3, 0x31, 0x11, 0xbe, 0xdb, 0x77, 0xf7, 0x7b, 0xc3, 0xe7,
	0x6b, 0x9f, 0x3f, 0xd6, 0x18, 0x6c, 0xb1, 0xe8, 0x06, 0x40, 0xca, 0x59, 0x4c, 0x84, 0x60, 0x5c,
	0xf8, 0x4d, 0xcd, 0xac, 0xb7, 0xfc, 0x23, 0x0b, 0xc3, 0x15, 0x06, 0x1a, 0x40, 0x4b, 0xd0, 0x64,
	0x2e, 0xfc, 0x96, 0xa6, 0x5e, 0xa9, 0x7f, 0x28, 0x4d, 0xe6, 0x38, 0xc7, 0x29, 0xc2, 0x8a, 0x92,
	0xfb, 0xc2, 0x6f, 0x1f, 0x43, 0x38, 0xa2, 0xe4, 0x3e, 0xce, 0x71, 0xe8, 0x1d, 0xe8, 0xa9, 0xc1,
	0xd8, 0x38, 0xd7, 0xd1, 0xb4, 0x97, 0xb6, 0xd2, 0x8c, 0x83, 0x55, 0x0e, 0xba, 0x0e, 0x5d, 0x3d,
	0xd5, 0x86, 0x7a, 0xfa, 0x80, 0x17, 0xb7, 0x1f, 0xa0, 0x8c, 0x2d, 0xf1, 0xe8, 0x26, 0xf4, 0x52,
	0xc2, 0x05, 0x15, 0x92, 0x24, 0x31, 0xf1, 0xbb, 0xfa, 0x72, 0xfb, 0xf5, 0xaf, 0xa8, 0xc4, 0xe1,
	0x2a, 0x29, 0xf8, 0xcd, 0x01, 0x6f, 0x44, 0xa6, 0x51, 0xb6, 0x90, 0x02, 0xbd, 0x00, 0xdd, 0x34,
	0xe2, 0x92, 0xea, 0x9b, 0x54, 0x97, 0xec, 0xe2, 0x72, 0x41, 0xdd, 0x34, 0x27, 0xe9, 0x82, 0xc6,
	0x51, 0x71, 0xd3, 0x2e, 0xae, 0x2e, 0xa9, 0xf8, 0x90, 0xdf, 0xa4, 0xc4, 0x44, 0xa3, 0x1e, 0xa3,
	0x37, 0xa1, 0xcb, 0x89, 0x24, 0x89, 0xe6, 0xe4, 0xf1, 0x77, 0x25, 0xcc, 0x95, 0x14, 0x5a, 0x25,
	0x85, 0x23, 0xa3, 0x24, 0x5c, 0x62, 0xd1, 0x35, 0xe8, 0x08, 0x32, 0x5b, 0xaa, 0xb0, 0x6d, 0x9d,
	0x44, 0xb3, 0xc8, 0xe0, 0x07, 0x07, 0x9e, 0xb2, 0x82, 0xbb, 0x95, 0x4c, 0xd9, 0xba, 0xa0, 0x9c,
	0x87, 0x15, 0x54, 0xe3, 0xe1, 0x04, 0xe5, 0x3e, 0xaa, 0xa0, 0x3e, 0x85, 0xd6, 0xad, 0x24, 0xcd,
	0x24, 0xba, 0x0d, 0x3b, 0x92, 0xa5, 0x34, 0x1e, 0x91, 0x29, 0x4d, 0xca, 0x37, 0xde, 0x1b, 0xbe,
	0x52, 0x7b, 0xd8, 0xc7, 0x0f, 0x62, 0xf1, 0x3a, 0x39, 0x38, 0x82, 0xe6, 0x7b, 0x8c, 0x26, 0x67,
	0x7e, 0xee, 0x67, 0xd0, 0xfe, 0x80, 0xb1, 0x79, 0x96, 0x9e, 0xf9, 0xc9, 0x23, 0x40, 0x1f, 0x12,
	0x21, 0xa2, 0x19, 0x29, 0x17, 0x85, 0xca, 0x8e, 0xf6, 0x7e, 0x7d, 0xa7, 0xef, 0xaa, 0xec, 0x68,
	0xe7, 0x2a, 0xbe, 0xa2, 0x15, 0x67, 0x7e, 0x43, 0xaf, 0xeb, 0x71, 0xf0, 0x16, 0x78, 0xe6, 0x94,
	0x47, 0xe7, 0x7e, 0x0b, 0xed, 0x3b, 0x99, 0x7c, 0x0c, 0xb7, 0x71, 0x72, 0x56, 0x0c, 0x8e, 0xe0,
	0x42, 0xfe, 0xec, 0x31, 0x91, 0x92, 0x26, 0x33, 0x81, 0x7c, 0xe8, 0xa4, 0x51, 0x3c, 0x8f, 0x66,
	0x36, 0x4c, 0xed, 0x54, 0xd9, 0x9e, 0x46, 0xf2, 0x9e, 0x39, 0x46, 0x8f, 0xd1, 0x73, 0xd0, 0x5e,
	0xb2, 0x49, 0xb6, 0xb0, 0x6a, 0x33, 0xb3, 0xe0, 0x57, 0x07, 0x7a, 0x15, 0xb5, 0x9f, 0xb9, 0x67,
	0x53, 0xb8, 0xac, 0x97, 0x0e, 0x39, 0xd1, 0xda, 0xab, 0x9c, 0xdb, 0xd0, 0xe7, 0x5e, 0xdd, 0x7e,
	0xee, 0x26, 0x07, 0x6f, 0x3b, 0x2c, 0xf8, 0xce, 0x85, 0x6e, 0x91, 0xd8, 0x6b, 0x2b, 0xcf, 0x55,
	0xb8, 0x38, 0xe3, 0x2c, 0x4b, 0x95, 0x8a, 0xef, 0xac, 0x08, 0xe7, 0x74, 0x62, 0x2b, 0xe6, 0xe6,
	0xc6, 0xfa, 0x8d, 0xb8, 0x9b, 0x75, 0x6a, 0x08, 0x6d, 0xaa, 0xa4, 0x69, 0x8b, 0xcd, 0x6e, 0xad,
	0x23, 0x5a, 0xbd, 0xd8, 0x20, 0x55, 0x6d, 0x5b, 0x68, 0x75, 0xd8, 0x32, 0x53, 0x5f, 0xdb, 0x72,
	0x05, 0x61, 0x8b, 0x55, 0xa5, 0xe6, 0x2b, 0x46, 0x93, 0xe3, 0x4b, 0x8d, 0x92, 0x33, 0xce, 0x71,
	0xea, 0x39, 0x4c, 0x47, 0x8b, 0x2d, 0x33, 0xf5, 0xcf, 0xc9, 0x23, 0x0a, 0x5b, 0xec, 0x7a, 0x85,
	0xf0, 0x4e, 0x53, 0x21, 0x7e, 0x6c, 0x40, 0x67, 0x9c, 0xa7, 0xc1, 0x53, 0x36, 0x00, 0x7b, 0x00,
	0x45, 0x02, 0xcc, 0x7b, 0x80, 0x2e, 0xae, 0xac, 0xa0, 0xeb, 0xd0, 0xce, 0x0d, 0x36, 0xf5, 0xe1,
	0xe5, 0x63, 0x7c, 0xb3, 0x6a, 0xc1, 0x86, 0x82, 0x6e, 0x80, 0x37, 0x31, 0xf5, 0xcb, 0xd4, 0x89,
	0xe0, 0xd8, 0xc0, 0xd6, 0x48, 0x5c, 0x70, 0xd0, 0x21, 0x78, 0x4b, 0x93, 0x3f, 0xfc, 0xb6, 0xe6,
	0xbf, 0x5e, 0xcb, 0xdf, 0x4c, 0x55, 0xb8, 0x20, 0x06, 0xdf, 0x3b, 0xd0, 0x54, 0x35, 0xf9, 0x94,
	0x2f, 0xa8, 0x46, 0xa3, 0xee, 0xbf, 0xc9, 0xac, 0xbf, 0x38, 0xd0, 0xce, 0x3b, 0x8c, 0x73, 0x2b,
	0xff, 0x3f, 0x1c, 0xb8, 0xbc, 0x85, 0xa4, 0xe2, 0xa9, 0xe8, 0x4a, 0x84, 0xe9, 0x53, 0x2a, 0x2b,
	0xaa, 0x0c, 0x98, 0xae, 0x44, 0x98, 0x2e, 0xa5, 0x98, 0xab, 0x24, 0xab, 0x22, 0x2f, 0x8a, 0xf3,
	0xda, 0xed, 0x61, 0x3b, 0xfd, 0x8f, 0x1b, 0x95, 0xdf, 0x1d, 0x78, 0xfa, 0x81, 0x90, 0xfc, 0x1f,
	0x34, 0x5f, 0x9f, 0xc0, 0xce, 0x5a, 0xfc, 0xa8, 0xd7, 0x6d, 0x44, 0x62, 0x6b, 0x9a, 0x99, 0x16,
	0xe6, 0x36, 0x2a, 0xe6, 0x3e, 0x0b, 0x2d, 0x1d, 0x0f, 0xc6, 0x87, 0x7c, 0xa2, 0x3e, 0xa2, 0x9a,
	0xaa, 0xfd, 0x3d, 0xb7, 0xb1, 0xfc, 0x97, 0x03, 0x9e, 0xed, 0xdf, 0x6b, 0x33, 0x44, 0x8d, 0x63,
	0x8d, 0xc7, 0xe4, 0x98, 0x7b, 0x86, 0x8e, 0xad, 0x67, 0xb6, 0xe6, 0x66, 0x97, 0xf3, 0xb7, 0x03,
	0x50, 0x7e, 0xfb, 0x3c, 0x59, 0xce, 0x0f, 0x29, 0x78, 0xf6, 0x5b, 0x04, 0x7d, 0x01, 0x17, 0xde,
	0x25, 0xd2, 0xd4, 0x51, 0xfd, 0x65, 0x52, 0xef, 0xde, 0xda, 0x1f, 0x84, 0xdd, 0x57, 0x4f, 0x40,
	0xe5, 0xff, 0x14, 0x6e, 0x06, 0x9f, 0x83, 0xdd, 0x5f, 0x1d, 0xfc, 0xd4, 0xb8, 0xf4, 0xbe, 0x21,
	0x59, 0x60, 0x78, 0x74, 0x70, 0xb7, 0xad, 0xa5, 0x7b, 0xed, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf9, 0x26, 0x3b, 0x68, 0x05, 0x11, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiscoverClient is the client API for Discover service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscoverClient interface {
	GetServiceInfo(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
}

type discoverClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoverClient(cc grpc.ClientConnInterface) DiscoverClient {
	return &discoverClient{cc}
}

func (c *discoverClient) GetServiceInfo(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, "/kafmesh.discover.v1.Discover/GetServiceInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoverServer is the server API for Discover service.
type DiscoverServer interface {
	GetServiceInfo(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
}

// UnimplementedDiscoverServer can be embedded to have forward compatible implementations.
type UnimplementedDiscoverServer struct {
}

func (*UnimplementedDiscoverServer) GetServiceInfo(ctx context.Context, req *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceInfo not implemented")
}

func RegisterDiscoverServer(s *grpc.Server, srv DiscoverServer) {
	s.RegisterService(&_Discover_serviceDesc, srv)
}

func _Discover_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoverServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kafmesh.discover.v1.Discover/GetServiceInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoverServer).GetServiceInfo(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Discover_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kafmesh.discover.v1.Discover",
	HandlerType: (*DiscoverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServiceInfo",
			Handler:    _Discover_GetServiceInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kafmesh/discover/v1/discover_api.proto",
}
