// Code generated by protoc-gen-go. DO NOT EDIT.
// source: kafmesh/watch/v1/operation.proto

package watchv1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Input is the input message that triggered the processor.
type Input struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{0}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Input) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Input) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Join is a join action.
type Join struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Join) Reset()         { *m = Join{} }
func (m *Join) String() string { return proto.CompactTextString(m) }
func (*Join) ProtoMessage()    {}
func (*Join) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{1}
}

func (m *Join) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Join.Unmarshal(m, b)
}
func (m *Join) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Join.Marshal(b, m, deterministic)
}
func (m *Join) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Join.Merge(m, src)
}
func (m *Join) XXX_Size() int {
	return xxx_messageInfo_Join.Size(m)
}
func (m *Join) XXX_DiscardUnknown() {
	xxx_messageInfo_Join.DiscardUnknown(m)
}

var xxx_messageInfo_Join proto.InternalMessageInfo

func (m *Join) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Join) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Join) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Lookup is a lookup action.
type Lookup struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lookup) Reset()         { *m = Lookup{} }
func (m *Lookup) String() string { return proto.CompactTextString(m) }
func (*Lookup) ProtoMessage()    {}
func (*Lookup) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{2}
}

func (m *Lookup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lookup.Unmarshal(m, b)
}
func (m *Lookup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lookup.Marshal(b, m, deterministic)
}
func (m *Lookup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lookup.Merge(m, src)
}
func (m *Lookup) XXX_Size() int {
	return xxx_messageInfo_Lookup.Size(m)
}
func (m *Lookup) XXX_DiscardUnknown() {
	xxx_messageInfo_Lookup.DiscardUnknown(m)
}

var xxx_messageInfo_Lookup proto.InternalMessageInfo

func (m *Lookup) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Lookup) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Lookup) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Lookup) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// GetState is a persistence action.
type GetState struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetState) Reset()         { *m = GetState{} }
func (m *GetState) String() string { return proto.CompactTextString(m) }
func (*GetState) ProtoMessage()    {}
func (*GetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{3}
}

func (m *GetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetState.Unmarshal(m, b)
}
func (m *GetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetState.Marshal(b, m, deterministic)
}
func (m *GetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetState.Merge(m, src)
}
func (m *GetState) XXX_Size() int {
	return xxx_messageInfo_GetState.Size(m)
}
func (m *GetState) XXX_DiscardUnknown() {
	xxx_messageInfo_GetState.DiscardUnknown(m)
}

var xxx_messageInfo_GetState proto.InternalMessageInfo

func (m *GetState) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *GetState) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *GetState) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// SetState is a persistence action.
type SetState struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetState) Reset()         { *m = SetState{} }
func (m *SetState) String() string { return proto.CompactTextString(m) }
func (*SetState) ProtoMessage()    {}
func (*SetState) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{4}
}

func (m *SetState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetState.Unmarshal(m, b)
}
func (m *SetState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetState.Marshal(b, m, deterministic)
}
func (m *SetState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetState.Merge(m, src)
}
func (m *SetState) XXX_Size() int {
	return xxx_messageInfo_SetState.Size(m)
}
func (m *SetState) XXX_DiscardUnknown() {
	xxx_messageInfo_SetState.DiscardUnknown(m)
}

var xxx_messageInfo_SetState proto.InternalMessageInfo

func (m *SetState) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *SetState) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *SetState) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Output is an output action.
type Output struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{5}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *Output) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Output) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Output) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Action is a streaming action a processor takes during an operation.
type Action struct {
	// Types that are valid to be assigned to Action:
	//	*Action_ActionJoin
	//	*Action_ActionLookup
	//	*Action_ActionGetState
	//	*Action_ActionSetState
	//	*Action_ActionOutput
	Action               isAction_Action `protobuf_oneof:"action"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Action) Reset()         { *m = Action{} }
func (m *Action) String() string { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()    {}
func (*Action) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{6}
}

func (m *Action) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Action.Unmarshal(m, b)
}
func (m *Action) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Action.Marshal(b, m, deterministic)
}
func (m *Action) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Action.Merge(m, src)
}
func (m *Action) XXX_Size() int {
	return xxx_messageInfo_Action.Size(m)
}
func (m *Action) XXX_DiscardUnknown() {
	xxx_messageInfo_Action.DiscardUnknown(m)
}

var xxx_messageInfo_Action proto.InternalMessageInfo

type isAction_Action interface {
	isAction_Action()
}

type Action_ActionJoin struct {
	ActionJoin *Join `protobuf:"bytes,1,opt,name=action_join,json=actionJoin,proto3,oneof"`
}

type Action_ActionLookup struct {
	ActionLookup *Lookup `protobuf:"bytes,2,opt,name=action_lookup,json=actionLookup,proto3,oneof"`
}

type Action_ActionGetState struct {
	ActionGetState *GetState `protobuf:"bytes,3,opt,name=action_get_state,json=actionGetState,proto3,oneof"`
}

type Action_ActionSetState struct {
	ActionSetState *SetState `protobuf:"bytes,4,opt,name=action_set_state,json=actionSetState,proto3,oneof"`
}

type Action_ActionOutput struct {
	ActionOutput *Output `protobuf:"bytes,5,opt,name=action_output,json=actionOutput,proto3,oneof"`
}

func (*Action_ActionJoin) isAction_Action() {}

func (*Action_ActionLookup) isAction_Action() {}

func (*Action_ActionGetState) isAction_Action() {}

func (*Action_ActionSetState) isAction_Action() {}

func (*Action_ActionOutput) isAction_Action() {}

func (m *Action) GetAction() isAction_Action {
	if m != nil {
		return m.Action
	}
	return nil
}

func (m *Action) GetActionJoin() *Join {
	if x, ok := m.GetAction().(*Action_ActionJoin); ok {
		return x.ActionJoin
	}
	return nil
}

func (m *Action) GetActionLookup() *Lookup {
	if x, ok := m.GetAction().(*Action_ActionLookup); ok {
		return x.ActionLookup
	}
	return nil
}

func (m *Action) GetActionGetState() *GetState {
	if x, ok := m.GetAction().(*Action_ActionGetState); ok {
		return x.ActionGetState
	}
	return nil
}

func (m *Action) GetActionSetState() *SetState {
	if x, ok := m.GetAction().(*Action_ActionSetState); ok {
		return x.ActionSetState
	}
	return nil
}

func (m *Action) GetActionOutput() *Output {
	if x, ok := m.GetAction().(*Action_ActionOutput); ok {
		return x.ActionOutput
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Action) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Action_ActionJoin)(nil),
		(*Action_ActionLookup)(nil),
		(*Action_ActionGetState)(nil),
		(*Action_ActionSetState)(nil),
		(*Action_ActionOutput)(nil),
	}
}

// Operation is a processor operation trigged by an input.
type Operation struct {
	StartTime            *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Input                *Input               `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Actions              []*Action            `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Operation) Reset()         { *m = Operation{} }
func (m *Operation) String() string { return proto.CompactTextString(m) }
func (*Operation) ProtoMessage()    {}
func (*Operation) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e03c41f74ef6ebf, []int{7}
}

func (m *Operation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Operation.Unmarshal(m, b)
}
func (m *Operation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Operation.Marshal(b, m, deterministic)
}
func (m *Operation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Operation.Merge(m, src)
}
func (m *Operation) XXX_Size() int {
	return xxx_messageInfo_Operation.Size(m)
}
func (m *Operation) XXX_DiscardUnknown() {
	xxx_messageInfo_Operation.DiscardUnknown(m)
}

var xxx_messageInfo_Operation proto.InternalMessageInfo

func (m *Operation) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Operation) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

func (m *Operation) GetInput() *Input {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *Operation) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Input)(nil), "kafmesh.watch.v1.Input")
	proto.RegisterType((*Join)(nil), "kafmesh.watch.v1.Join")
	proto.RegisterType((*Lookup)(nil), "kafmesh.watch.v1.Lookup")
	proto.RegisterType((*GetState)(nil), "kafmesh.watch.v1.GetState")
	proto.RegisterType((*SetState)(nil), "kafmesh.watch.v1.SetState")
	proto.RegisterType((*Output)(nil), "kafmesh.watch.v1.Output")
	proto.RegisterType((*Action)(nil), "kafmesh.watch.v1.Action")
	proto.RegisterType((*Operation)(nil), "kafmesh.watch.v1.Operation")
}

func init() { proto.RegisterFile("kafmesh/watch/v1/operation.proto", fileDescriptor_5e03c41f74ef6ebf) }

var fileDescriptor_5e03c41f74ef6ebf = []byte{
	// 478 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0x9c, 0xc4, 0x49, 0x26, 0x50, 0x45, 0x56, 0x05, 0x56, 0x2e, 0x44, 0x39, 0x71, 0x61,
	0xad, 0x04, 0x71, 0xe8, 0x09, 0x91, 0x03, 0x84, 0xb6, 0xa8, 0x91, 0x83, 0x28, 0xe2, 0x92, 0x6e,
	0xdd, 0xad, 0x6b, 0x12, 0x7b, 0xad, 0xec, 0xda, 0x88, 0xbf, 0xc3, 0x91, 0x3f, 0x05, 0x3f, 0x05,
	0xed, 0xec, 0xda, 0x46, 0x98, 0x88, 0x0f, 0xe5, 0xe6, 0xc9, 0xbe, 0xf7, 0x76, 0xde, 0xbc, 0x9d,
	0xc0, 0x78, 0x43, 0x6f, 0x63, 0x26, 0xee, 0xbc, 0x4f, 0x54, 0x06, 0x77, 0x5e, 0x3e, 0xf5, 0x78,
	0xca, 0x76, 0x54, 0x46, 0x3c, 0x21, 0xe9, 0x8e, 0x4b, 0xee, 0x0c, 0x0d, 0x82, 0x20, 0x82, 0xe4,
	0xd3, 0xd1, 0xa3, 0x90, 0xf3, 0x70, 0xcb, 0x3c, 0x3c, 0xbf, 0xce, 0x6e, 0x3d, 0x19, 0xc5, 0x4c,
	0x48, 0x1a, 0xa7, 0x9a, 0x32, 0x79, 0x03, 0x9d, 0xd7, 0x49, 0x9a, 0x49, 0xe7, 0x18, 0x3a, 0x92,
	0xa7, 0x51, 0xe0, 0x36, 0xc7, 0xcd, 0xc7, 0x7d, 0x5f, 0x17, 0x8e, 0x0b, 0xdd, 0x98, 0x09, 0x41,
	0x43, 0xe6, 0x5a, 0xf8, 0x7b, 0x51, 0x2a, 0x7c, 0x4e, 0xb7, 0x19, 0x73, 0x5b, 0x1a, 0x8f, 0xc5,
	0xe4, 0x1c, 0xda, 0xa7, 0x3c, 0x4a, 0x0e, 0xa4, 0x76, 0x05, 0xf6, 0x39, 0xe7, 0x9b, 0x2c, 0xfd,
	0x67, 0xbd, 0x21, 0xb4, 0x36, 0xec, 0xb3, 0x51, 0x53, 0x9f, 0xd5, 0x0d, 0xed, 0x9f, 0x6f, 0x58,
	0x42, 0xef, 0x15, 0x93, 0x2b, 0x49, 0x25, 0x3b, 0x50, 0xcf, 0x4b, 0xe8, 0xad, 0x0e, 0xab, 0x78,
	0x05, 0xf6, 0x45, 0x26, 0xff, 0x27, 0xa3, 0xbf, 0x9d, 0xc2, 0x37, 0x0b, 0xec, 0x17, 0x81, 0x7a,
	0x48, 0xce, 0x09, 0x0c, 0x28, 0x7e, 0xad, 0x3f, 0xf2, 0x28, 0xc1, 0x8b, 0x06, 0xb3, 0x07, 0xe4,
	0xd7, 0x87, 0x45, 0x54, 0xca, 0x8b, 0x86, 0x0f, 0x1a, 0x8c, 0x99, 0x3f, 0x87, 0xfb, 0x86, 0xba,
	0xc5, 0xd0, 0xb0, 0x9b, 0xc1, 0xcc, 0xad, 0x93, 0x75, 0xa8, 0x8b, 0x86, 0x7f, 0x4f, 0x13, 0x4c,
	0xc8, 0x2f, 0x61, 0x68, 0x04, 0x42, 0x26, 0xd7, 0x42, 0x8d, 0x10, 0x7b, 0x1f, 0xcc, 0x46, 0x75,
	0x8d, 0x22, 0xb6, 0x45, 0xc3, 0x3f, 0xd2, 0xac, 0x32, 0xc8, 0x4a, 0x47, 0x94, 0x3a, 0xed, 0x7d,
	0x3a, 0xab, 0x9a, 0x4e, 0x19, 0x5f, 0x65, 0x88, 0xe3, 0xfc, 0xdd, 0xce, 0x3e, 0x43, 0x3a, 0x9f,
	0xca, 0x90, 0xae, 0xe7, 0x3d, 0xb0, 0x75, 0x3d, 0xf9, 0xde, 0x84, 0xfe, 0x45, 0xb1, 0xad, 0xce,
	0x09, 0x80, 0x90, 0x74, 0x27, 0xd7, 0x6a, 0x1b, 0xcd, 0x8c, 0x47, 0x44, 0xaf, 0x2a, 0x29, 0x56,
	0x95, 0xbc, 0x2d, 0x56, 0xd5, 0xef, 0x23, 0x5a, 0xd5, 0xce, 0x33, 0xe8, 0xb1, 0xe4, 0x46, 0x13,
	0xad, 0x3f, 0x12, 0xbb, 0x2c, 0xb9, 0x41, 0xda, 0x13, 0xe8, 0x44, 0x6a, 0xcd, 0xcd, 0x3c, 0x1f,
	0xd6, 0x2d, 0xe0, 0xbf, 0x80, 0xaf, 0x51, 0xce, 0x0c, 0xba, 0xba, 0x71, 0xe1, 0xb6, 0xc7, 0xad,
	0xdf, 0x7b, 0xd6, 0x0f, 0xc6, 0x2f, 0x80, 0xf3, 0x53, 0x38, 0x0e, 0x78, 0x5c, 0xc3, 0xcd, 0x8f,
	0x4a, 0xdf, 0x4b, 0xd5, 0xe0, 0xb2, 0xf9, 0xa1, 0x8b, 0x67, 0xf9, 0xf4, 0x8b, 0xd5, 0x3a, 0xbb,
	0x7c, 0xff, 0xd5, 0x1a, 0x9e, 0x19, 0xce, 0x25, 0x72, 0xde, 0x4d, 0xaf, 0x6d, 0xf4, 0xf2, 0xf4,
	0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb, 0x9f, 0x61, 0x06, 0xf3, 0x04, 0x00, 0x00,
}
