package generator

import (
	"io"
	"strings"
	"text/template"

	"github.com/iancoleman/strcase"
	"github.com/pkg/errors"
	"github.com/syncromatics/kafmesh/pkg/models"
)

var (
	emitterTemplate = template.Must(template.New("").Parse(`// Code generated by kafmesh-gen. DO NOT EDIT.

package {{ .Package }}

import (
	"context"

	"github.com/burdiyan/kafkautil"
	"github.com/lovoo/goka"
	"github.com/pkg/errors"

	"github.com/syncromatics/kafmesh/pkg/runner"

	"{{ .Import }}"
)

type {{ .Name }}_Emitter interface {
	Emit(message {{ .Name }}_Emitter_Message) error
	EmitBulk(ctx context.Context, messages []{{ .Name }}_Emitter_Message) error
}

type {{ .Name }}_Emitter_impl struct {
	emitter *runner.Emitter
}

type {{ .Name }}_Emitter_Message struct {
	Key string
	Value *{{ .MessageType }}
}

type impl_{{ .Name }}_Emitter_Message struct {
	msg {{ .Name }}_Emitter_Message
}

func (m *impl_{{ .Name }}_Emitter_Message) Key() string {
	return m.msg.Key
}

func (m *impl_{{ .Name }}_Emitter_Message) Value() interface{} {
	return m.msg.Value
}

func New_{{ .Name }}_Emitter(options runner.ServiceOptions) (*{{ .Name }}_Emitter_impl, error) {
	brokers := options.Brokers
	protoWrapper := options.ProtoWrapper

	codec, err := protoWrapper.Codec("{{ .TopicName }}", &{{ .MessageType }}{})
	if err != nil {
		return nil, errors.Wrap(err, "failed to create codec")
	}

	emitter, err := goka.NewEmitter(brokers,
		goka.Stream("{{ .TopicName }}"),
		codec,
		goka.WithEmitterHasher(kafkautil.MurmurHasher))

	if err != nil {
		return nil, errors.Wrap(err, "failed creating emitter")
	}

	return &{{ .Name }}_Emitter_impl{
		emitter: runner.NewEmitter(emitter),
	}, nil
}

func (e *{{ .Name }}_Emitter_impl) Watch(ctx context.Context) func() error {
	return e.emitter.Watch(ctx)
}

func (e *{{ .Name }}_Emitter_impl) Emit(message {{ .Name }}_Emitter_Message) error {
	return e.emitter.Emit(message.Key, message.Value)
}

func (e *{{ .Name }}_Emitter_impl) EmitBulk(ctx context.Context, messages []{{ .Name }}_Emitter_Message) error {
	b := []runner.EmitMessage{}
	for _, m := range messages {
		b = append(b, &impl_{{ .Name }}_Emitter_Message{msg: m})
	}
	return e.emitter.EmitBulk(ctx, b)
}
`))
)

type emitterOptions struct {
	Package     string
	Import      string
	Name        string
	TopicName   string
	MessageType string
}

func generateEmitter(writer io.Writer, emitter *emitterOptions) error {
	err := emitterTemplate.Execute(writer, emitter)
	if err != nil {
		return errors.Wrap(err, "failed to execute emitter template")
	}
	return nil
}

func buildEmitterOptions(pkg string, mod string, modelsPath string, service *models.Service, emitter models.Emitter) (*emitterOptions, error) {
	options := &emitterOptions{
		Package: pkg,
	}

	var name strings.Builder
	nameFrags := strings.Split(emitter.Message, ".")
	for _, f := range nameFrags[1:] {
		name.WriteString(strcase.ToCamel(f))
	}

	options.TopicName = emitter.ToTopicName(service)
	options.Name = name.String()
	options.Import = emitter.ToPackage(service)
	options.MessageType = nameFrags[len(nameFrags)-2] + "." + strcase.ToCamel(nameFrags[len(nameFrags)-1])

	return options, nil
}
