// Code generated by MockGen. DO NOT EDIT.
// Source: ./processorOutput.go

// Package resolvers_test is a generated GoMock package.
package resolvers_test

import (
	gomock "github.com/golang/mock/gomock"
	model "github.com/syncromatics/kafmesh/internal/graph/model"
	reflect "reflect"
)

// MockProcessorOutputLoader is a mock of ProcessorOutputLoader interface
type MockProcessorOutputLoader struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorOutputLoaderMockRecorder
}

// MockProcessorOutputLoaderMockRecorder is the mock recorder for MockProcessorOutputLoader
type MockProcessorOutputLoaderMockRecorder struct {
	mock *MockProcessorOutputLoader
}

// NewMockProcessorOutputLoader creates a new mock instance
func NewMockProcessorOutputLoader(ctrl *gomock.Controller) *MockProcessorOutputLoader {
	mock := &MockProcessorOutputLoader{ctrl: ctrl}
	mock.recorder = &MockProcessorOutputLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockProcessorOutputLoader) EXPECT() *MockProcessorOutputLoaderMockRecorder {
	return m.recorder
}

// ProcessorByOutput mocks base method
func (m *MockProcessorOutputLoader) ProcessorByOutput(arg0 int) (*model.Processor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessorByOutput", arg0)
	ret0, _ := ret[0].(*model.Processor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessorByOutput indicates an expected call of ProcessorByOutput
func (mr *MockProcessorOutputLoaderMockRecorder) ProcessorByOutput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessorByOutput", reflect.TypeOf((*MockProcessorOutputLoader)(nil).ProcessorByOutput), arg0)
}

// TopicByOutput mocks base method
func (m *MockProcessorOutputLoader) TopicByOutput(arg0 int) (*model.Topic, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TopicByOutput", arg0)
	ret0, _ := ret[0].(*model.Topic)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TopicByOutput indicates an expected call of TopicByOutput
func (mr *MockProcessorOutputLoaderMockRecorder) TopicByOutput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TopicByOutput", reflect.TypeOf((*MockProcessorOutputLoader)(nil).TopicByOutput), arg0)
}
